// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core_platform_interface/firebase_core_platform_interface.dart' show FirebaseOptions;
// TODO: Run 'flutter pub get' to install firebase_core package
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZAAa6H1Kv3lLb2cqtg3ZGZTwqivsJXBE',
    appId: '1:719098584641:web:4b662acbd6ccc4f15b70c0',
    messagingSenderId: '719098584641',
    projectId: 'fit-life-1d65b',
    authDomain: 'fit-life-1d65b.firebaseapp.com',
    storageBucket: 'fit-life-1d65b.firebasestorage.app',
    measurementId: 'G-2QKZWGQ24K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4mTlanAxbn9_C27oXZNbFNNyYnG-rLfY',
    appId: '1:719098584641:android:6b2ae630afb9ee705b70c0',
    messagingSenderId: '719098584641',
    projectId: 'fit-life-1d65b',
    storageBucket: 'fit-life-1d65b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG_MWcXvprCmkqTTdL60TwdklDQqSauY8',
    appId: '1:719098584641:ios:2f7dd7bc3204113a5b70c0',
    messagingSenderId: '719098584641',
    projectId: 'fit-life-1d65b',
    storageBucket: 'fit-life-1d65b.firebasestorage.app',
    iosBundleId: 'com.example.hello',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBG_MWcXvprCmkqTTdL60TwdklDQqSauY8',
    appId: '1:719098584641:ios:2f7dd7bc3204113a5b70c0',
    messagingSenderId: '719098584641',
    projectId: 'fit-life-1d65b',
    storageBucket: 'fit-life-1d65b.firebasestorage.app',
    iosBundleId: 'com.example.hello',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZAAa6H1Kv3lLb2cqtg3ZGZTwqivsJXBE',
    appId: '1:719098584641:web:3d3a219a7835a1975b70c0',
    messagingSenderId: '719098584641',
    projectId: 'fit-life-1d65b',
    authDomain: 'fit-life-1d65b.firebaseapp.com',
    storageBucket: 'fit-life-1d65b.firebasestorage.app',
    measurementId: 'G-D9SQ7E83F0',
  );
}
